### ISSUE TITLE
Make a release on the releases tab

### ISSUE THREAD

**Issue by Karthik99999** [Thealexbarney/PqSave#1]
It would make it easier for people to get. While I know how to compile it, others don't know and don't want to install the programs required to do so.

**Comment by Ofdas23** [comment]
Like me. I dont know what to do..

**Comment by Thealexbarney** [comment]
Added a [release](https://github.com/Thealexbarney/PqSave/releases/tag/2018-06-04)

**Comment by Ofdas23** [comment]
Thank you, now I have to find a way to use it on my Mac... WineBottler won’t work.. I tried it already
