### ISSUE TITLE
.NET Core SDK Build failed on Mac

### ISSUE THREAD

**Issue by wendyliga** [Thealexbarney/PqSave#13]
i had already install .NET Core SDK and retrive this error when i try to build the project

/usr/local/share/dotnet/sdk/2.1.202/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/path/PqSave-master/PqSaveSkeleton/obj/project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project. [/path/PqSave-master/PqSaveSkeleton/PqSaveSkeleton.csproj]

any clue ?

**Comment by Thealexbarney** [comment]
The project file for the example skeleton program doesn't target `netcoreapp2.0` (Although it could).

The actual program will still build even if the skeleton doesn't

**Comment by wendyliga** [comment]
@Thealexbarney it won't build. i got empty build folder

it's does not matter right now. Find out that releases and just use the prebuild on repo 

thanks
