### ISSUE TITLE
Sorry, didnt know how to contact you. So using this. :(

### ISSUE THREAD

**Issue by realTobby** [Thealexbarney/PqSave#2]
Hello :)
I would love to understand the process of location the correct addresses inside the byte array.
AFAIK the decrypted save file is differently sized for everybody. How does it work that you can locate the correct address? For example: my player name is stored inside the offset of: 0x2570 but for other people it will be 0x3680. Is it understandable what I mean? Sorry to disturb and missuse the issue tab. An explanation would be golden tho :)

**Comment by Thealexbarney** [comment]
The game serializes the save structure using ZeroFormatter and saves it as a file. Reading the save involves deserializing the file back into the save object
