### ISSUE TITLE
Build fails with linux   

### ISSUE THREAD

**Issue by fennectech** [Thealexbarney/PqSave#4]
[fennectech@Aluminum ~/PqSave]$  xbuild PqSave.sln 

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 5.12.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 6/4/2018 5:09:48 PM.
__________________________________________________
/home/fennectech/PqSave/PqSave.sln:  warning : /home/fennectech/PqSave/PqSave/PqSave.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/home/fennectech/PqSave/PqSave.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.
Project "/home/fennectech/PqSave/PqSave.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Debug|Any CPU".
	Target Build:
/home/fennectech/PqSave/PqSave/PqSave.csproj: error : /home/fennectech/PqSave/PqSave/PqSave.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/fennectech/PqSave/PqSave.sln".-- FAILED
Done building project "/home/fennectech/PqSave/PqSave.sln".-- FAILED

Build FAILED.

Warnings:

/home/fennectech/PqSave/PqSave.sln:  warning : /home/fennectech/PqSave/PqSave/PqSave.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/home/fennectech/PqSave/PqSave.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.

Errors:

/home/fennectech/PqSave/PqSave.sln (default targets) ->
(Build target) ->

	/home/fennectech/PqSave/PqSave/PqSave.csproj: error : /home/fennectech/PqSave/PqSave/PqSave.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  

	 2 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:00.8125330

{17:09} Mon Jun 04
[fennectech@Aluminum ~/PqSave]$

**Comment by Thealexbarney** [comment]
Use Visual Studio or the .NET Core SDK to build the project

**Comment by fennectech** [comment]
thanks    :D i did not know of the  .net core SDK    its effing cool
